services:
    ssl:
        image: nginx:latest
        depends_on:
            - nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./certs:/root/ssl/
            - ./docker/nginx/conf/:/etc/nginx/conf.d/:ro

    php:
        extra_hosts: []
        environment:
            TRUSTED_PROXIES: "127.0.0.1,REMOTE_ADDR"

    nginx:
        extra_hosts: []
